version: '1.0'
GUI:
  title: '&3升级你的属性！'
  name: '&a你的属性如下'
  line: '&3**************************'
  style: '   &a%ATTRNAME%&3: &1%ATTRVALUE%'
database:
  enable: true
  host: localhost
  port: 3306
  username: 'root'
  password: ''
ui:
  warn: true
  bdmsg: '&a*你触发了嗜血 吸取 &3%VALUE%&a的伤害*'
  cmsg: '&a*你触发了暴击 造成 &3%VALUE%&a的伤害*'
  hmmsg: '&3%PLAYERNAME%&aMISS&2了你的攻击！'
  mmsg: '&2你&aMISS&2了来自&3%PLAYERNAME%&2的攻击!'
test:
  useleveluphealthchange: false
  debug: false
count: 1
list:
  1:
    name: '&B属性强化宝石一阶'
    lore:
      - '&3***********************'
      - '                         '
      - '&a  随机强化一个属性'
      - '&a    概率10%'
      - '&a   强化能力10%'
      - '                         '
      - '&3***********************'
    id: 276
    chance: 10
    strong: 10
    attr: 10
    money: 100
more:
    ATTACK:
      name: '&a攻击加成'
      maxlevel: 1000
      default: 0
    DEFENSE:
      name: '&a防御'
      maxlevel: 1000
      default: 0
    CRIT:
      name: '&a暴击几率'
      maxlevel: 1000
      default: 10
    CRIT_DMG:
      name: '&a暴击伤害'
      maxlevel: 1000
      default: 50
    DODGE:
      name: '&a闪避'
      maxlevel: 1000
      default: 5
    BLOOD_DRINK:
      name: '&a嗜血几率'
      maxlevel: 1000
      default: 0
    BLOOD_DRINK_DMG:
      name: '&a嗜血量'
      maxlevel: 1000
      default: 5
    PLAYER_DAMAGED:
      name: '&a对玩家伤害加成'
      maxlevel: 1000
      default: 0
    ENTITY_DAMAGED:
      name: '&a对怪物伤害加成'
      maxlevel: 1000
      default: 0
    EX_HEAL:
      name: '&a额外生命恢复'
      maxlevel: 1000
      default: 10
    HEALTH:
      name: '&a生命加成'
      maxlevel: 1000
      default: 10
    BRAMBLES:
      name: '&a荆棘'
      maxlevel: 1000
      default: 5